import "./styles/globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { AuthGuard } from "@/components/auth-guard/auth-guard";
import { UsersProvider } from "@/contexts/users.context";
import Header from "@/components/core/header";
import Footer from "@/components/core/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sign in",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="h-full"
    >
      <head></head>
      <body className={`${inter.className} h-full`}>
        <AuthGuard>
          <UsersProvider>
            <Header />
            {children}
          </UsersProvider>
          <Footer />
        </AuthGuard>
      </body>
    </html>
  );
}
